"""Batch runner: test many stores, emit an aggregate leaderboard.

    python -m agentiqa.batch stores.txt -o RESULTS.md

stores.txt = one store URL per line (blank lines and #comments ignored).
Produces the headline stat ("X% of stores dead-end before checkout") plus a
per-store funnel table. This is the shareable artifact — the number is the point.

Safety is unchanged from the single-store runner: the agent never enters payment
data, never creates accounts, never submits an order. Only run against stores you
own or have permission to test.
"""

import argparse
import sys
import time

from . import checks, report

MILESTONES = ["product_found", "added_to_cart", "checkout_reached"]


def read_urls(path: str) -> list:
    urls = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if line:
                urls.append(line)
    return urls


def load_shopper(driver: str):
    import os
    if driver == "auto":
        driver = "api" if os.environ.get("ANTHROPIC_API_KEY") else "cli"
    if driver == "cli":
        from . import shopper_cli as mod
    else:
        from . import shopper as mod
    return mod, driver


def furthest(milestones: list) -> str:
    """Deepest funnel stage reached, or 'none'."""
    reached = [m for m in MILESTONES if m in milestones]
    return reached[-1] if reached else "none"


def aggregate(results: list) -> dict:
    """Pure: turn per-store results into headline stats. results = list of dicts
    with keys milestones (list), error (bool), static_pass (int), static_total (int)."""
    ok = [r for r in results if not r.get("error")]
    n = len(ok)
    counts = {m: sum(1 for r in ok if m in r.get("milestones", [])) for m in MILESTONES}
    checkout = counts["checkout_reached"]
    pct = lambda k: round(100 * k / n) if n else 0
    return {
        "total": len(results),
        "tested": n,
        "errored": len(results) - n,
        "counts": counts,
        "reached_checkout": checkout,
        "failed_checkout": n - checkout,
        "pct_reached": pct(checkout),
        "pct_failed": pct(n - checkout) if n else 0,
        "pct_product": pct(counts["product_found"]),
        "pct_cart": pct(counts["added_to_cart"]),
    }


def render_md(results: list, stats: dict, goal: str) -> str:
    s = stats
    store_word = "store" if s["tested"] == 1 else "stores"
    lines = [
        "# Can AI agents buy from real stores?",
        "",
        f"An AI shopping agent was sent through **{s['tested']} {store_word}** with one goal: "
        f"*{goal}* — find a product, add to cart, reach checkout (stopping before payment).",
        "",
        f"## {s['pct_failed']}% of stores dead-ended the agent before checkout.",
        "",
        f"- Reached a product page: **{s['pct_product']}%** ({s['counts']['product_found']}/{s['tested']})",
        f"- Added to cart: **{s['pct_cart']}%** ({s['counts']['added_to_cart']}/{s['tested']})",
        f"- Reached checkout: **{s['pct_reached']}%** ({s['reached_checkout']}/{s['tested']})",
        "",
        "## Per-store results",
        "",
        "| Store | Product | Cart | Checkout | Static score | Where it stopped |",
        "| --- | :-: | :-: | :-: | :-: | --- |",
    ]
    tick = lambda m, r: "✅" if m in r.get("milestones", []) else "—"
    for r in results:
        url = r["url"]
        if r.get("error"):
            lines.append(f"| {url} | ⚠️ | ⚠️ | ⚠️ | — | error: {r.get('error')} |")
            continue
        stopped = furthest(r.get("milestones", []))
        note = (r.get("summary", "") or "").replace("\n", " ").replace("|", "/")[:160]
        lines.append(
            f"| {url} | {tick('product_found', r)} | {tick('added_to_cart', r)} "
            f"| {tick('checkout_reached', r)} | {r.get('static_pass', 0)}/{r.get('static_total', 0)} "
            f"| stopped at: {stopped}. {note} |"
        )
    if s["errored"]:
        lines += ["", f"_{s['errored']} store(s) errored out and are excluded from the percentages._"]
    lines += ["", "---", "",
              "Generated by [AgentiQA](https://github.com/) — run it on your own store: "
              "`python -m agentiqa https://your-store.com`.", ""]
    return "\n".join(lines)


def run_batch(urls, goal, driver="auto", delay=3.0, log=print) -> list:
    shopper, driver = load_shopper(driver)
    log(f"Batch: {len(urls)} stores, {driver} driver, goal={goal!r}")
    results = []
    for i, url in enumerate(urls, 1):
        log(f"\n[{i}/{len(urls)}] {url}")
        row = {"url": url, "milestones": [], "summary": "", "error": None}
        try:
            static = checks.run_static_checks(url)
            row["static_pass"] = sum(1 for c in static if c["passed"])
            row["static_total"] = len(static)
            agent = shopper.run_shopper(url, goal, log=lambda m: None)
            row["milestones"] = agent["milestones"]
            row["summary"] = agent["summary"]
            log(f"    reached: {furthest(agent['milestones'])}")
        except Exception as e:
            row["error"] = str(e)[:200]
            log(f"    ERROR: {row['error']}")
        results.append(row)
        if i < len(urls):
            time.sleep(delay)  # be polite to the stores
    return results


def main():
    p = argparse.ArgumentParser(prog="agentiqa.batch",
                                description="Run the shopper agent across many stores; emit an aggregate leaderboard.")
    p.add_argument("urls_file", help="Text file: one store URL per line (# comments ok)")
    p.add_argument("--goal", default="Buy any in-stock product from this store.")
    p.add_argument("--driver", choices=["auto", "api", "cli"], default="auto")
    p.add_argument("--delay", type=float, default=3.0, help="Seconds between stores (politeness)")
    p.add_argument("-o", "--out", default="RESULTS.md")
    args = p.parse_args()

    urls = read_urls(args.urls_file)
    if not urls:
        print("No URLs found.", file=sys.stderr)
        return 1
    results = run_batch(urls, args.goal, args.driver, args.delay)
    stats = aggregate(results)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(render_md(results, stats, args.goal))
    print(f"\n{stats['pct_failed']}% of {stats['tested']} stores dead-ended before checkout.")
    print(f"Leaderboard: {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
